# Generated by Django 3.2.23 on 2023-12-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicación', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='id',
        ),
        migrations.AlterField(
            model_name='persona',
            name='num_exp',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
